name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify Docker installation
        run: docker --version

      - name: Build Docker image
        run: docker build -t flask-api .
      
      - name: Run placeholder test step
        run: |
          echo "Running simulated tests..."
          docker run flask-api echo "All tests passed (simulated)"